---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

[https://github.com/WinVector/PreparingDataWorkshop](https://github.com/WinVector/PreparingDataWorkshop)
 
These are instructions how to prepare to work along with the examples from the workshop:

> "Preparing Data for Analysis using R: Basic through Advanced Techniques (WORKSHOP)"
authors: John Mount & Nina Zumel, Win-Vector, LLC 
>
> Abstract for "Preparing data for analysis using R: basic through advanced techniques" John Mount / Nina Zumel.
>
> Data quality is the biggest determiner of data science project success or failure.    Preparing data for analysis is one of the most important, laborious, and yet neglected aspects of data science.  Many of the routine steps can be automated in a principled manner.  This workshop will lay out the fundamentals of preparing data and provide interactive demonstrations in the open source R analysis environment.
>
> We will cover what commonly goes wrong, and how to detect and fix it.  We start with seemingly operational issues (many variables, "wide data", missing values, large cardinality categoricals, novel categorical levels) and how to correct them in in real world data.  We work through this and demonstrate that careless correction of these issues can lead to statistically invalid machine learning procedures that give poor results in production.  We then introduce automated procedures that are both practical and statistically valid.
>
> We show that "y aware pre-processing" is required to reliably pre-process data for analysis and that such pre-processing is statistically unpopular as it breaks the common statistical precautions such as test/train split and cross validation.  We then demonstrate how "simulated out of sample" procedures "or cross frame procedures" (as used in super-learning and stacking) are sufficient to allow powerful "y aware pre-processing" and nested models in a statistically sound manner.  With better statistical procedures more powerful tools can be reliably used leading to better predictive modeling results.
>
> Participants can download materials from https://github.com/WinVector/PreparingDataWorkshop and either follow along during the workshop, or at their leisure.  We will work examples using  R  ( https://cran.r-project.org ), RStudio ( https://www.rstudio.com ), and a few packages (named in README.md on the Github repository).  Participants can re-run all the demonstrations whenever they want.

You can download all files in this Github repository, and prepare your machine before trying the examples.  In the workshop we will walk through all examples as pre-prepared knitr or R markdown sheets, so it will not be necissary to bring a laptop to attend the workshop.

To run all of the examples you will need a machine with a current version of [R](https://cran.r-project.org), and [RStudio](https://www.rstudio.com) installed.

To install some of the additional packages you will need your system's compiler tools installed (often c,c++, and FORTRAN).  How to do this varies by system  and is beyond the scope of the workshop.

*   On Linux it is a matter of installing the correct development packages (some Ubuntu instructions [here](https://github.com/JohnMount/ec2R/blob/master/ec2steps.bash)).
*   On OSX you need [XCode](https://developer.apple.com/xcode/) and ["command line tools"](http://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/) installed and active.
*   On windows you may need [RTools](https://cran.r-project.org/bin/windows/Rtools/) and/or [Microsoft Visual Studio](https://msdn.microsoft.com/en-us/vstudio/cc136611.aspx).


The additional R packages you want installed are the following:

```{r eval=FALSE}
install.packages(c('caret',
                   'devtools',
                   'e1071',
                   'gbm',
                   'glmnet',
                   'ggplot2',
                   'kernlab',
                   'knitr',
                   'plyr',
                   'pROC',
                   'randomForest',
                   'reshape2',
                   'rpart',
                   'snow',
                   'vtreat'))
devtools::install_github('WinVector/WVPlots')
```

John Mount will be presenting and co-author Nina Zumel has (with the generous
sponsorhip of Microsoft) prepared a whitepaper outlining the material (available [here](http://winvector.github.io/DataPrep/EN-CNTNT-Whitepaper-Data-Prep-Using-R.pdf)).

Much of this material was presented at ODSC 2015 ([complete video here](https://www.youtube.com/watch?v=Dd6idYl8mu8), [slides here](https://github.com/WinVector/PreparingDataWorkshop/tree/master/ODSC_2015_Slides)).
